collections:
  getting-started:
      output: true
  developer-guide:
     output: true
  integrator-guide:
     output: true
  references:
     output: true

algolia:
  application_id: 'Y7BGGRAPHC'
  index_name:     'riversand'
  search_only_api_key: '6007828d06dd7900f9af359f4e88149c'
