collections:
  getting-started:
      output: true
  developer-guide:
     output: true
  integrator-guide:
     output: true
  references:
     output: true

algolia:
  application_id: 'ATFLB4CP7X'
  index_name: 'riversand'
  search_only_api_key: 'ce94e2f5b4ab95657bfdc9bcc62a7529'
